# Generated by Django 3.2.9 on 2021-11-24 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='upload_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 2, 8, 10, 483543)),
        ),
    ]
