# Generated by Django 3.2.9 on 2021-11-25 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_doc_upload_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='upload_at',
        ),
    ]
