# Generated by Django 3.2.9 on 2021-11-25 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_doc_upload_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
